from django.contrib import admin, messages
from django.utils import timezone
from django.utils.html import format_html

from .models import AuthCode, AuthCodeUsage


class AuthCodeUsageInline(admin.TabularInline):
    """
    Inline display of code usages with IP addresses.
    """
    model = AuthCodeUsage
    extra = 0
    readonly_fields = ('ip_address', 'user_agent', 'used_at')
    can_delete = False
    
    def has_add_permission(self, request, obj=None):
        return False


@admin.register(AuthCode)
class AuthCodeAdmin(admin.ModelAdmin):
    """
    Admin interface for AuthCode model (Create/Edit/Delete enabled).
    """

    list_display = (
        "code",
        "status_badge",
        "used_count",
        "unique_users_display",
        "created_by",
        "created_at",
    )
    inlines = [AuthCodeUsageInline]
    list_filter = ("status", "created_at")
    search_fields = ("code", "created_by__email")
    ordering = ("-created_at",)
    date_hierarchy = "created_at"
    
    def get_queryset(self, request):
        """
        Optimize queryset with prefetch_related to avoid N+1 queries.
        """
        qs = super().get_queryset(request)
        return qs.select_related('created_by').prefetch_related('usages')

    # Read-only fields always (even on edit)
    readonly_fields = (
        "code",
        "used_count",
        "unique_users_display",
        "created_at",
        "updated_at",
        "last_used_at",
    )

    fieldsets = (
        ("Code Information", {"fields": ("code",)}),
        ("Usage & Status", {
            "fields": ("status", "used_count", "unique_users_display", "last_used_at")
        }),
        ("Metadata", {"fields": ("created_by", "created_at", "updated_at")}),
    )

    actions = ("action_revoke", "action_activate")

    # ---------- UI helpers ----------
    def status_badge(self, obj):
        if obj is None:
            return '-'
        
        colors = {
            "active": "#16a34a",   # green
            "revoked": "#ef4444",  # red
        }
        color = colors.get(obj.status, "#6b7280")  # gray
        label = obj.get_status_display()
        return format_html(
            '<span style="background:{};color:#fff;padding:3px 10px;border-radius:999px;font-size:12px;">{}</span>',
            color,
            label,
        )

    status_badge.short_description = "Status"

    def unique_users_display(self, obj):
        """
        Display the count of unique IP addresses.
        """
        if obj is None:
            return '-'
        
        try:
            count = obj.unique_users_count
        except Exception:
            count = 0
        
        if count == 0:
            return format_html('<span style="color:#6b7280;">{}</span>', '0 users')
        
        user_text = 'user' if count == 1 else 'users'
        return format_html(
            '<span style="background:#3b82f6;color:#fff;padding:3px 10px;border-radius:999px;font-size:12px;">{}</span>',
            f'{count} {user_text}'
        )
    
    unique_users_display.short_description = "Unique Users (IP)"

    # ---------- Create/Edit behavior ----------
    def get_readonly_fields(self, request, obj=None):
        """
        Make created_by read-only on edit (set automatically on create).
        """
        ro = list(super().get_readonly_fields(request, obj=obj))
        if obj:  # editing existing
            ro.append("created_by")
        return ro

    def save_model(self, request, obj, form, change):
        """
        On create: set created_by automatically to the current admin user.
        Ensure code is generated only once and doesn't change on subsequent saves.
        """
        if not change:  # Creating new object
            if not obj.created_by_id:
                obj.created_by = request.user
            # Code will be auto-generated by the model's default
        super().save_model(request, obj, form, change)
        
        # Show success message with the generated code
        if not change:
            self.message_user(
                request, 
                f'Authentication code created successfully! Code: {obj.code}',
                level=messages.SUCCESS
            )
    
    def get_form(self, request, obj=None, **kwargs):
        """
        Customize the form. On add page, pre-generate the code to display it.
        """
        form = super().get_form(request, obj, **kwargs)
        
        # If adding a new object (obj is None), we need to handle the code display
        if obj is None:
            # The code will be generated when the object is saved
            # We'll show a message in get_fieldsets instead
            pass
            
        return form
    
    def get_fieldsets(self, request, obj=None):
        """
        Customize fieldsets based on add vs change.
        """
        if obj is None:  # Adding new object
            # Show a simpler view for adding - code will be auto-generated on save
            return (
                ("Settings", {
                    "fields": (),
                    "description": "The authentication code will be automatically generated when you save. Active codes can be used unlimited times until revoked."
                }),
                ("Created By", {"fields": ("created_by",)}),
            )
        else:  # Editing existing object
            # After creation, show full fieldsets with the generated code
            return self.fieldsets

    def clean(self):
        """
        (Optional) You could add model-level validation, but not required here.
        """
        return super().clean()

    # ---------- Permissions (Create/Edit/Delete enabled) ----------
    def has_add_permission(self, request):
        """
        Allow create in admin.
        """
        return request.user.is_active and request.user.is_staff

    def has_change_permission(self, request, obj=None):
        """
        Allow edit in admin.
        """
        return request.user.is_active and request.user.is_staff

    def has_delete_permission(self, request, obj=None):
        """
        Allow delete in admin.
        You can tighten this if you want (e.g., disallow deleting used codes).
        """
        return request.user.is_active and request.user.is_staff

    # ---------- Admin Actions ----------
    @admin.action(description="Revoke selected codes")
    def action_revoke(self, request, queryset):
        count = 0
        for code in queryset:
            if code.status != "revoked":
                code.revoke()
                count += 1
        self.message_user(request, f"Revoked {count} code(s).", level=messages.SUCCESS)

    @admin.action(description="Activate selected codes")
    def action_activate(self, request, queryset):
        updated = queryset.exclude(status="active").update(status="active", updated_at=timezone.now())
        self.message_user(request, f"Activated {updated} code(s).", level=messages.SUCCESS)


@admin.register(AuthCodeUsage)
class AuthCodeUsageAdmin(admin.ModelAdmin):
    """
    Admin interface for viewing authentication code usage logs.
    """
    list_display = ('auth_code', 'ip_address', 'used_at')
    list_filter = ('used_at', 'auth_code')
    search_fields = ('ip_address', 'auth_code__code')
    readonly_fields = ('auth_code', 'ip_address', 'user_agent', 'used_at')
    ordering = ('-used_at',)
    date_hierarchy = 'used_at'
    
    def has_add_permission(self, request):
        return False
    
    def has_change_permission(self, request, obj=None):
        return False
    
    def has_delete_permission(self, request, obj=None):
        return request.user.is_superuser
