# Generated by Django 6.0.1 on 2026-01-18 05:24

import authcodes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=authcodes.models.generate_auth_code, help_text='Unique 8-digit authentication code', max_length=8, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this code can be used')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used')),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this code was successfully used', null=True)),
                ('created_by', models.ForeignKey(help_text='Super admin who created this code', on_delete=django.db.models.deletion.CASCADE, related_name='created_auth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Code',
                'verbose_name_plural': 'Authentication Codes',
                'db_table': 'auth_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'status'], name='auth_codes_code_abaab5_idx')],
            },
        ),
    ]
