# Generated by Django 6.0.1 on 2026-01-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcode',
            name='max_uses',
        ),
        migrations.AlterField(
            model_name='authcode',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20),
        ),
    ]
