# Generated by Django 6.0.1 on 2026-01-18 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcodes', '0002_remove_authcode_max_uses_alter_authcode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the browser', null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When this code was used')),
                ('auth_code', models.ForeignKey(help_text='The authentication code that was used', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='authcodes.authcode')),
            ],
            options={
                'verbose_name': 'Authentication Code Usage',
                'verbose_name_plural': 'Authentication Code Usages',
                'db_table': 'auth_code_usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['auth_code', 'ip_address'], name='auth_code_u_auth_co_0ad028_idx'), models.Index(fields=['auth_code', 'used_at'], name='auth_code_u_auth_co_87c03f_idx'), models.Index(fields=['ip_address'], name='auth_code_u_ip_addr_c8f356_idx')],
            },
        ),
    ]
