# Generated by Django 6.0.1 on 2026-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video')], default='pdf', max_length=50)),
                ('category', models.CharField(choices=[('book', 'Book'), ('publication', 'Publication'), ('research', 'Research')], default='book', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='العربية', max_length=100)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('audio', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='publications/covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/documents/')),
                ('date', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-id'],
            },
        ),
    ]
