# Generated by Django 6.0.1 on 2026-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/audio/'),
        ),
        migrations.AddField(
            model_name='book',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/video/'),
        ),
    ]
