# Generated by Django 6.0.1 on 2026-05-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_audio_file_book_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='book', max_length=160),
        ),
    ]
