# Generated by Django 6.0.1 on 2026-05-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_category_relation_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='book.book')),
            ],
            options={
                'verbose_name': 'Book Summary',
                'verbose_name_plural': 'Book Summaries',
                'ordering': ['-id'],
            },
        ),
    ]
