# Generated by Django 6.0.1 on 2026-05-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_description'),
        ('book', '0006_publicationtextextraction'),
    ]

    operations = [
    ]
